---

- name: Config - watch files
  template:
    src=watch-files.json.j2
    dest=/etc/logstash-forwarder/{{ logstash_from_play }}.json
    owner={{ logstash_forwarder_user }}
    group={{ logstash_forwarder_group }}
    mode=0644
  notify: restart logstash-forwarder

- name: Config - remove watch files
  file:
    state=absent
    path=/etc/logstash-forwarder/{{ logstash_from_play }}.json
  with_items: "{{ logstash_forwarder_config_files_remove }}"
  notify: restart logstash-forwarder

